RegisterHook("/Script/Pal.PalGameStateInGame:BroadcastChatMessage", function(self, ChatMessage)
    chat_message = ChatMessage:get()
    message = chat_message.Message:ToString()
    sender = chat_message.Sender:ToString()
    date = os.date ("%Y-%m-%d %H:%M:%S")
    print(date .. " " .. sender .." said " .. message)
    local filehandler = io.open("PalChatLog.txt", "a")
    filehandler:write(date .. " " .. sender .. " said " .. message.."\n")
    filehandler:close()
end)
